autoload, "toml.i",
    toml_collect,
    toml_format_boolean,
    toml_format_float,
    toml_format_integer,
    toml_format_string,
    toml_format_timestamp,
    toml_key,
    toml_keys,
    toml_length,
    toml_load,
    toml_parse,
    toml_parse_file,
    toml_timestamp,
    toml_type;
